In [1]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# plcaceholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")

0 Cost:  16810.135 
Prediction:
 [33.339207 48.473778 43.310917 47.678696 38.811985]
------------------------------
10 Cost:  4.43913 
Prediction:
 [148.02638 186.30434 179.12546 195.57628 143.93916]
------------------------------
20 Cost:  4.263489 
Prediction:
 [148.38124 186.71599 179.53882 196.02534 144.25035]
------------------------------
30 Cost:  4.2418556 
Prediction:
 [148.39012 186.7119  179.54248 196.02829 144.2444 ]
------------------------------
40 Cost:  4.220334 
Prediction:
 [148.39795 186.70656 179.5449  196.02989 144.23753]
------------------------------
50 Cost:  4.198909 
Prediction:
 [148.40576 186.70122 179.54732 196.03146 144.23068]
------------------------------
60 Cost:  4.1776123 
Prediction:
 [148.41354 186.69589 179.54971 196.03302 144.22385]
------------------------------
70 Cost:  4.156437 
Prediction:
 [148.42131 186.69061 179.55212 196.0346  144.21703]
------------------------------
80 Cost:  4.135355 
Prediction:
 [148.42905 186.6853  179.55453 196.036

910 Cost:  2.729834 
Prediction:
 [149.00433 186.29233 179.73254 196.15128 143.70605]
------------------------------
920 Cost:  2.7164552 
Prediction:
 [149.01051 186.2881  179.73447 196.15251 143.70067]
------------------------------
930 Cost:  2.703141 
Prediction:
 [149.01668 186.28389 179.73636 196.15373 143.69528]
------------------------------
940 Cost:  2.6899061 
Prediction:
 [149.02281 186.27968 179.73827 196.15492 143.68991]
------------------------------
950 Cost:  2.676724 
Prediction:
 [149.02896 186.27551 179.74017 196.15614 143.68456]
------------------------------
960 Cost:  2.663637 
Prediction:
 [149.03508 186.27135 179.74207 196.15738 143.67923]
------------------------------
970 Cost:  2.6506255 
Prediction:
 [149.04115 186.26718 179.74396 196.15855 143.67389]
------------------------------
980 Cost:  2.6376483 
Prediction:
 [149.04724 186.263   179.74582 196.15976 143.66858]
------------------------------
990 Cost:  2.6247432 
Prediction:
 [149.05331 186.25887 179.

 [149.55196 185.91853 179.9024  196.25786 143.22934]
------------------------------
1930 Cost:  1.6770041 
Prediction:
 [149.55669 185.91531 179.90388 196.25877 143.22525]
------------------------------
1940 Cost:  1.6692884 
Prediction:
 [149.56139 185.91211 179.90535 196.25967 143.22118]
------------------------------
1950 Cost:  1.661607 
Prediction:
 [149.56609 185.90892 179.9068  196.26057 143.21712]
------------------------------
1960 Cost:  1.6539685 
Prediction:
 [149.57076 185.90572 179.90825 196.26146 143.21306]
------------------------------
1970 Cost:  1.646376 
Prediction:
 [149.57542 185.90254 179.90971 196.26234 143.20903]
------------------------------
1980 Cost:  1.638808 
Prediction:
 [149.58008 185.89935 179.91116 196.26324 143.20499]
------------------------------
1990 Cost:  1.6313051 
Prediction:
 [149.58472 185.89621 179.9126  196.26413 143.20097]
------------------------------
2000 Cost:  1.6238229 
Prediction:
 [149.58934 185.89304 179.91403 196.26498 143.19696

2620 Cost:  1.2307062 
Prediction:
 [149.8535  185.71294 179.99623 196.31465 142.9689 ]
------------------------------
2630 Cost:  1.2253853 
Prediction:
 [149.8574  185.71027 179.99745 196.31537 142.96555]
------------------------------
2640 Cost:  1.220073 
Prediction:
 [149.86131 185.7076  179.99864 196.31609 142.96217]
------------------------------
2650 Cost:  1.2148099 
Prediction:
 [149.8652  185.70496 179.99988 196.31682 142.95883]
------------------------------
2660 Cost:  1.2095649 
Prediction:
 [149.8691  185.70232 180.00108 196.31754 142.9555 ]
------------------------------
2670 Cost:  1.2043473 
Prediction:
 [149.87297 185.69968 180.00229 196.31825 142.95218]
------------------------------
2680 Cost:  1.1991507 
Prediction:
 [149.87683 185.69704 180.0035  196.31897 142.94884]
------------------------------
2690 Cost:  1.1939816 
Prediction:
 [149.88069 185.69441 180.00468 196.31967 142.94553]
------------------------------
2700 Cost:  1.1888626 
Prediction:
 [149.88452 18

3310 Cost:  0.9225894 
Prediction:
 [150.1005  185.54471 180.07327 196.35965 142.75723]
------------------------------
3320 Cost:  0.9188954 
Prediction:
 [150.10376 185.54248 180.0743  196.36023 142.75444]
------------------------------
3330 Cost:  0.91524935 
Prediction:
 [150.10701 185.5403  180.07533 196.36082 142.7517 ]
------------------------------
3340 Cost:  0.91159755 
Prediction:
 [150.11024 185.53807 180.07632 196.36137 142.74892]
------------------------------
3350 Cost:  0.90797794 
Prediction:
 [150.11346 185.53587 180.07732 196.36195 142.74614]
------------------------------
3360 Cost:  0.9043765 
Prediction:
 [150.1167  185.53369 180.07834 196.36255 142.74341]
------------------------------
3370 Cost:  0.9007951 
Prediction:
 [150.1199  185.5315  180.07935 196.36311 142.74066]
------------------------------
3380 Cost:  0.8972262 
Prediction:
 [150.12312 185.52931 180.08035 196.3637  142.73795]
------------------------------
3390 Cost:  0.8936802 
Prediction:
 [150.1263

In [2]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# plcaceholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")

0 Cost:  232778.16 
Prediction:
 [[-267.75082]
 [-335.97415]
 [-323.73227]
 [-353.21185]
 [-259.1311 ]]
------------------------------
10 Cost:  42.918285 
Prediction:
 [[158.98859]
 [176.98141]
 [181.6674 ]
 [197.15826]
 [132.13432]]
------------------------------
20 Cost:  40.569115 
Prediction:
 [[160.25522]
 [178.5503 ]
 [183.18906]
 [198.81783]
 [133.34044]]
------------------------------
30 Cost:  40.351692 
Prediction:
 [[160.23456]
 [178.57182]
 [183.18619]
 [198.81723]
 [133.36632]]
------------------------------
40 Cost:  40.13537 
Prediction:
 [[160.2101 ]
 [178.58867]
 [183.17874]
 [198.81163]
 [133.3886 ]]
------------------------------
50 Cost:  39.920197 
Prediction:
 [[160.18567]
 [178.60544]
 [183.17128]
 [198.80602]
 [133.41078]]
------------------------------
60 Cost:  39.706287 
Prediction:
 [[160.16132]
 [178.62215]
 [183.16385]
 [198.80042]
 [133.4329 ]]
------------------------------
70 Cost:  39.49352 
Prediction:
 [[160.13701]
 [178.63881]
 [183.15643]
 [198.79

1030 Cost:  23.607494 
Prediction:
 [[158.08765]
 [180.04585]
 [182.53114]
 [198.32181]
 [135.31891]]
------------------------------
1040 Cost:  23.48168 
Prediction:
 [[158.06898]
 [180.05865]
 [182.52544]
 [198.31749]
 [135.33589]]
------------------------------
1050 Cost:  23.35655 
Prediction:
 [[158.05038]
 [180.07143]
 [182.51976]
 [198.31316]
 [135.35283]]
------------------------------
1060 Cost:  23.232115 
Prediction:
 [[158.03183]
 [180.08415]
 [182.51411]
 [198.30887]
 [135.36974]]
------------------------------
1070 Cost:  23.108286 
Prediction:
 [[158.01334]
 [180.09688]
 [182.50847]
 [198.30458]
 [135.3866 ]]
------------------------------
1080 Cost:  22.985195 
Prediction:
 [[157.99489]
 [180.10956]
 [182.50285]
 [198.30031]
 [135.4034 ]]
------------------------------
1090 Cost:  22.862736 
Prediction:
 [[157.97649]
 [180.12218]
 [182.49724]
 [198.29602]
 [135.42017]]
------------------------------
1100 Cost:  22.74089 
Prediction:
 [[157.95813]
 [180.13478]
 [182.4916

2120 Cost:  13.220853 
Prediction:
 [[156.32596]
 [181.25586]
 [181.99425]
 [197.91061]
 [136.92612]]
------------------------------
2130 Cost:  13.151113 
Prediction:
 [[156.3121 ]
 [181.26541]
 [181.99005]
 [197.90738]
 [136.9388 ]]
------------------------------
2140 Cost:  13.081766 
Prediction:
 [[156.29826]
 [181.27489]
 [181.98582]
 [197.9041 ]
 [136.95142]]
------------------------------
2150 Cost:  13.012759 
Prediction:
 [[156.28448]
 [181.28438]
 [181.98163]
 [197.90088]
 [136.96404]]
------------------------------
2160 Cost:  12.944203 
Prediction:
 [[156.27074]
 [181.29381]
 [181.97745]
 [197.89764]
 [136.9766 ]]
------------------------------
2170 Cost:  12.87594 
Prediction:
 [[156.25702]
 [181.30322]
 [181.97327]
 [197.89441]
 [136.98914]]
------------------------------
2180 Cost:  12.808062 
Prediction:
 [[156.24333]
 [181.3126 ]
 [181.96909]
 [197.89119]
 [137.00163]]
------------------------------
2190 Cost:  12.740573 
Prediction:
 [[156.22972]
 [181.32199]
 [181.96

3240 Cost:  7.34838 
Prediction:
 [[154.98639]
 [182.1765 ]
 [181.58672]
 [197.59308]
 [138.15349]]
------------------------------
3250 Cost:  7.310331 
Prediction:
 [[154.97618]
 [182.18352]
 [181.5836 ]
 [197.59062]
 [138.16287]]
------------------------------
3260 Cost:  7.272502 
Prediction:
 [[154.96599]
 [182.1905 ]
 [181.5805 ]
 [197.58818]
 [138.17223]]
------------------------------
3270 Cost:  7.2348733 
Prediction:
 [[154.95584]
 [182.1975 ]
 [181.57742]
 [197.58575]
 [138.18156]]
------------------------------
3280 Cost:  7.1974363 
Prediction:
 [[154.94571]
 [182.20447]
 [181.57436]
 [197.58333]
 [138.19087]]
------------------------------
3290 Cost:  7.160228 
Prediction:
 [[154.93561]
 [182.21141]
 [181.57129]
 [197.58092]
 [138.20015]]
------------------------------
3300 Cost:  7.123204 
Prediction:
 [[154.92554]
 [182.21834]
 [181.56822]
 [197.57852]
 [138.20941]]
------------------------------
3310 Cost:  7.0863786 
Prediction:
 [[154.9155 ]
 [182.22523]
 [181.56516]
