In [2]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 2.8743463 [[-0.4259668  -0.20594999 -0.33208537]
 [ 0.81815857  1.5363392  -1.4941758 ]
 [-0.12596472 -1.4122726   1.5989274 ]]
1 2.283538 [[-0.4359366  -0.2050738  -0.32299176]
 [ 0.77955216  1.5609298  -1.48016   ]
 [-0.15451677 -1.3385159   1.5537227 ]]
2 2.2197433 [[-0.4361631  -0.21448523 -0.31335384]
 [ 0.79850006  1.5258228  -1.4640009 ]
 [-0.13060237 -1.3194196   1.5107121 ]]
3 2.1786726 [[-0.4413075  -0.22023755 -0.30245712]
 [ 0.7892367   1.5124084  -1.4413232 ]
 [-0.13325284 -1.2807314   1.4746745 ]]
4 2.1416516 [[-0.4443984  -0.22836077 -0.291243  ]
 [ 0.792328    1.4851931  -1.4171993 ]
 [-0.12442021 -1.2551451   1.4402554 ]]
5 2.105853 [[-0.44887483 -0.23541562 -0.27971172]
 [ 0.7876318   1.4641805  -1.3914905 ]
 [-0.12279473 -1.2241751   1.4076599 ]]
6 2.070578 [[-0.45277405 -0.24315    -0.26807812]
 [ 0.78653556  1.4390991  -1.3653128 ]
 [-0.11771225 -1.1972917   1.375694  ]]
7 2.035644 [[-0.45714667 -0.25049883 -0.25635666]
 [ 0.78288335  1.416124   -1.3386854 ]
 [-0

Accuracy:  1.0


In [2]:
import tensorflow as tf
import numpy as np

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-10).minimize(cost)

# Correct prediction Test model
prediction = tf.argmax(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(201):
        cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)
    
    # predict
    print("Prediction: ", sess.run(prediction, feed_dict={X: x_test}))
    
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
1 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
2 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
3 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
4 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
5 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
6 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.46814746  0.5079432  -0.62223613]]
7 4.242146 [[ 0.09913177  0.3872115   0.15639298]
 [ 0.21949506  1.2800403   0.7673686 ]
 [-0.468

In [3]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  4318802700000.0 
Prediction:
 [[1466487.1]
 [2952215. ]
 [2322395.2]
 [1627979.9]
 [1918664.1]
 [1934813.1]
 [1773321.1]
 [2257800.2]]
1 Cost:  4.7449843e+27 
Prediction:
 [[-4.8590202e+13]
 [-9.7817058e+13]
 [-7.6949154e+13]
 [-5.3940943e+13]
 [-6.3572281e+13]
 [-6.4107357e+13]
 [-5.8756612e+13]
 [-7.4808843e+13]]
2 Cost:  inf 
Prediction:
 [[1.6105877e+21]
 [3.2422782e+21]
 [2.5505832e+21]
 [1.7879455e+21]
 [2.1071892e+21]
 [2.1249251e+21]
 [1.9475673e+21]
 [2.4796403e+21]]
3 Cost:  inf 
Prediction:
 [[-5.3385106e+28]
 [-1.0746969e+29]
 [-8.4542534e+28]
 [-5.9263867e+28]
 [-6.9845637e+28]
 [-7.0433511e+28]
 [-6.4554750e+28]
 [-8.2191022e+28]]
4 Cost:  inf 
Prediction:
 [[1.7695214e+36]
 [3.5622281e+36]
 [2.8022763e+36]
 [1.9643808e+36]
 [2.3151279e+36]
 [2.3346137e+36]
 [2.1397541e+36]
 [2.7243323e+36]]
5 Cost:  inf 
Prediction:
 [[-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]
 [-inf]]
6 Cost:  nan 
Prediction:
 [[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]

In [4]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility


def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)


xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

# very important. It does not work without it.
xy = min_max_scaler(xy)
print(xy)

'''
[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
'''

x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

# Launch the graph in a session.
with tf.Session() as sess:
    # Initializes global variables in the graph.
    sess.run(tf.global_variables_initializer())

    for step in range(101):
        _, cost_val, hy_val = sess.run(
            [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
        )
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]
0 Cost:  0.34438485 
Prediction:
 [[-0.05683047]
 [ 0.5287802 ]
 [ 0.5673416 ]
 [ 0.6226775 ]
 [ 0.5227794 ]
 [ 0.51509374]
 [ 0.87443906]
 [ 1.0080848 ]]
1 Cost:  0.34438235 
Prediction:
 [[-0.05682361]
 [ 0.52878374]
 [ 0.5673443 ]
 [ 0.62267905]
 [ 0.52278197]
 [ 0.51509595]
 [ 0.8744384 ]
 [ 1.0080831 ]]
2 Cost:  0.34437978 
Prediction:
 [[-0.0568167 ]
 [ 0.5287874 ]
 [ 0.5673469 ]
 [ 0.6226806 ]
 [ 0.5227844 ]
 [ 0.5150981 ]
 [ 0.87443775]
 [ 1.0080814 ]]
3 Cost:  0.34437728 
Prediction:
 [[-0.0568099 ]
 [ 0.5287909 ]
 [ 0.5