In [5]:
import tensorflow as tf
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

# plcaceholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")


0 Cost:  7008.4937 
Prediction:
 [230.22742 270.81607 269.83002 292.64737 206.40802]
------------------------------
10 Cost:  9.088853 
Prediction:
 [156.20651 181.87042 182.17892 197.1989  138.56923]
------------------------------
20 Cost:  8.976759 
Prediction:
 [155.97098 181.60924 181.91017 196.9076  138.37434]
------------------------------
30 Cost:  8.929007 
Prediction:
 [155.95874 181.61636 181.90582 196.9042  138.38411]
------------------------------
40 Cost:  8.881513 
Prediction:
 [155.94717 181.62427 181.90227 196.90167 138.39442]
------------------------------
50 Cost:  8.834252 
Prediction:
 [155.93565 181.63216 181.89874 196.89917 138.40475]
------------------------------
60 Cost:  8.7872715 
Prediction:
 [155.92418 181.64003 181.8952  196.89668 138.41504]
------------------------------
70 Cost:  8.740561 
Prediction:
 [155.91272 181.64787 181.8917  196.89417 138.42528]
------------------------------
80 Cost:  8.694105 
Prediction:
 [155.9013  181.65569 181.88818 196.891

960 Cost:  5.449935 
Prediction:
 [155.00793 182.2677  181.61386 196.69763 139.23499]
------------------------------
970 Cost:  5.4212446 
Prediction:
 [154.99895 182.27385 181.61111 196.69568 139.24301]
------------------------------
980 Cost:  5.3926926 
Prediction:
 [154.98999 182.27998 181.60835 196.69373 139.25102]
------------------------------
990 Cost:  5.3643155 
Prediction:
 [154.98106 182.2861  181.60562 196.6918  139.25902]
------------------------------
1000 Cost:  5.336095 
Prediction:
 [154.97215 182.29219 181.60289 196.68987 139.26698]
------------------------------
1010 Cost:  5.3079987 
Prediction:
 [154.96327 182.2983  181.60014 196.68794 139.27492]
------------------------------
1020 Cost:  5.2800603 
Prediction:
 [154.9544  182.30435 181.59741 196.68604 139.28285]
------------------------------
1030 Cost:  5.252309 
Prediction:
 [154.94559 182.31041 181.59473 196.68411 139.29076]
------------------------------
1040 Cost:  5.22465 
Prediction:
 [154.93675 182.31645 

1660 Cost:  3.7738814 
Prediction:
 [154.43446 182.66048 181.4377  196.57361 139.74757]
------------------------------
1670 Cost:  3.7542114 
Prediction:
 [154.42702 182.66557 181.4354  196.57199 139.75421]
------------------------------
1680 Cost:  3.7346902 
Prediction:
 [154.41962 182.67065 181.43314 196.57042 139.76085]
------------------------------
1690 Cost:  3.7152877 
Prediction:
 [154.41223 182.67572 181.43088 196.56883 139.76744]
------------------------------
1700 Cost:  3.6959586 
Prediction:
 [154.40485 182.68076 181.42859 196.56723 139.77402]
------------------------------
1710 Cost:  3.6767418 
Prediction:
 [154.3975  182.6858  181.42635 196.56564 139.7806 ]
------------------------------
1720 Cost:  3.6576126 
Prediction:
 [154.39017 182.69084 181.42409 196.56407 139.78714]
------------------------------
1730 Cost:  3.6386292 
Prediction:
 [154.38286 182.69583 181.42184 196.5625  139.79367]
------------------------------
1740 Cost:  3.619735 
Prediction:
 [154.37556 18

2380 Cost:  2.6000686 
Prediction:
 [153.94756 182.99396 181.28807 196.46886 140.18225]
------------------------------
2390 Cost:  2.586761 
Prediction:
 [153.94142 182.99814 181.28616 196.46753 140.1877 ]
------------------------------
2400 Cost:  2.5735264 
Prediction:
 [153.93532 183.00232 181.28427 196.46623 140.19315]
------------------------------
2410 Cost:  2.560378 
Prediction:
 [153.92923 183.00648 181.28241 196.46494 140.19858]
------------------------------
2420 Cost:  2.547298 
Prediction:
 [153.92316 183.01064 181.28053 196.46361 140.20398]
------------------------------
2430 Cost:  2.5343204 
Prediction:
 [153.91711 183.01477 181.2787  196.46233 140.20938]
------------------------------
2440 Cost:  2.521371 
Prediction:
 [153.91107 183.0189  181.27684 196.46103 140.21477]
------------------------------
2450 Cost:  2.5084946 
Prediction:
 [153.90506 183.02303 181.27496 196.45973 140.22014]
------------------------------
2460 Cost:  2.4957047 
Prediction:
 [153.89906 183.0

3090 Cost:  1.8144602 
Prediction:
 [153.55173 183.26494 181.1663  196.3842  140.53503]
------------------------------
3100 Cost:  1.8054209 
Prediction:
 [153.54668 183.26839 181.16476 196.38312 140.53954]
------------------------------
3110 Cost:  1.7964194 
Prediction:
 [153.54163 183.27184 181.16321 196.38205 140.544  ]
------------------------------
3120 Cost:  1.7874553 
Prediction:
 [153.53662 183.2753  181.16167 196.38097 140.5485 ]
------------------------------
3130 Cost:  1.7785482 
Prediction:
 [153.5316  183.27873 181.16014 196.37991 140.55296]
------------------------------
3140 Cost:  1.7697035 
Prediction:
 [153.52661 183.28214 181.15858 196.37883 140.5574 ]
------------------------------
3150 Cost:  1.7609036 
Prediction:
 [153.52162 183.28554 181.15706 196.37779 140.56184]
------------------------------
3160 Cost:  1.752133 
Prediction:
 [153.51666 183.28896 181.15552 196.37672 140.56627]
------------------------------
3170 Cost:  1.7434156 
Prediction:
 [153.51169 18

3810 Cost:  1.2735035 
Prediction:
 [153.22076 183.4915  181.06444 196.31392 140.82948]
------------------------------
3820 Cost:  1.2673957 
Prediction:
 [153.21663 183.49434 181.06317 196.31305 140.83319]
------------------------------
3830 Cost:  1.2613095 
Prediction:
 [153.21246 183.49716 181.06189 196.31215 140.83685]
------------------------------
3840 Cost:  1.2552397 
Prediction:
 [153.20833 183.5     181.06062 196.31126 140.84055]
------------------------------
3850 Cost:  1.2492069 
Prediction:
 [153.2042  183.50282 181.05934 196.31041 140.84421]
------------------------------
3860 Cost:  1.2432323 
Prediction:
 [153.20009 183.50563 181.05809 196.30954 140.84785]
------------------------------
3870 Cost:  1.2372609 
Prediction:
 [153.19598 183.50844 181.05681 196.30867 140.8515 ]
------------------------------
3880 Cost:  1.2313251 
Prediction:
 [153.1919  183.51126 181.05557 196.30782 140.85515]
------------------------------
3890 Cost:  1.2254303 
Prediction:
 [153.18782 1

In [7]:
import tensorflow as tf

x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

# plcaceholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")


0 Cost:  50810.406 
Prediction:
 [[354.35916]
 [423.0279 ]
 [418.44   ]
 [454.9719 ]
 [322.34808]]
------------------------------
10 Cost:  5.1906185 
Prediction:
 [[154.95741]
 [183.37741]
 [182.30023]
 [197.82236]
 [139.55829]]
------------------------------
20 Cost:  4.701228 
Prediction:
 [[154.34593]
 [182.65791]
 [181.58325]
 [197.0424 ]
 [139.01268]]
------------------------------
30 Cost:  4.6771 
Prediction:
 [[154.33594]
 [182.66132]
 [181.57861]
 [197.03816]
 [139.01845]]
------------------------------
40 Cost:  4.6530414 
Prediction:
 [[154.32777]
 [182.66692]
 [181.57613]
 [197.03625]
 [139.02588]]
------------------------------
50 Cost:  4.629115 
Prediction:
 [[154.31964]
 [182.6725 ]
 [181.57364]
 [197.03436]
 [139.0333 ]]
------------------------------
60 Cost:  4.605362 
Prediction:
 [[154.31155]
 [182.67807]
 [181.57117]
 [197.03249]
 [139.04068]]
------------------------------
70 Cost:  4.581713 
Prediction:
 [[154.30347]
 [182.68361]
 [181.5687 ]
 [197.0306 ]
 [139

1020 Cost:  2.8302467 
Prediction:
 [[153.62787]
 [183.14774]
 [181.36288]
 [196.87238]
 [139.66507]]
------------------------------
1030 Cost:  2.816193 
Prediction:
 [[153.62163]
 [183.15201]
 [181.36098]
 [196.8709 ]
 [139.67073]]
------------------------------
1040 Cost:  2.8022175 
Prediction:
 [[153.61543]
 [183.15627]
 [181.35909]
 [196.86943]
 [139.6764 ]]
------------------------------
1050 Cost:  2.788284 
Prediction:
 [[153.60922]
 [183.16052]
 [181.3572 ]
 [196.86797]
 [139.68207]]
------------------------------
1060 Cost:  2.774472 
Prediction:
 [[153.60307]
 [183.16475]
 [181.35533]
 [196.86652]
 [139.68773]]
------------------------------
1070 Cost:  2.760685 
Prediction:
 [[153.59691]
 [183.169  ]
 [181.35345]
 [196.86507]
 [139.69336]]
------------------------------
1080 Cost:  2.747015 
Prediction:
 [[153.59079]
 [183.17322]
 [181.3516 ]
 [196.8636 ]
 [139.69897]]
------------------------------
1090 Cost:  2.7333996 
Prediction:
 [[153.58466]
 [183.17741]
 [181.34972]

2080 Cost:  1.6928864 
Prediction:
 [[153.05437]
 [183.54192]
 [181.18843]
 [196.73604]
 [140.19096]]
------------------------------
2090 Cost:  1.684964 
Prediction:
 [[153.0497 ]
 [183.5451 ]
 [181.187  ]
 [196.73488]
 [140.19522]]
------------------------------
2100 Cost:  1.6770957 
Prediction:
 [[153.04506]
 [183.54831]
 [181.18561]
 [196.73378]
 [140.1995 ]]
------------------------------
2110 Cost:  1.6692429 
Prediction:
 [[153.04042]
 [183.5515 ]
 [181.18419]
 [196.73268]
 [140.20377]]
------------------------------
2120 Cost:  1.661451 
Prediction:
 [[153.0358 ]
 [183.55467]
 [181.18279]
 [196.73157]
 [140.20801]]
------------------------------
2130 Cost:  1.6537071 
Prediction:
 [[153.03119]
 [183.55783]
 [181.1814 ]
 [196.73047]
 [140.21225]]
------------------------------
2140 Cost:  1.6459898 
Prediction:
 [[153.0266 ]
 [183.56099]
 [181.18   ]
 [196.72935]
 [140.21648]]
------------------------------
2150 Cost:  1.6383146 
Prediction:
 [[153.02202]
 [183.56415]
 [181.178

3190 Cost:  1.0296781 
Prediction:
 [[152.60777]
 [183.84912]
 [181.05289]
 [196.62766]
 [140.60287]]
------------------------------
3200 Cost:  1.0253253 
Prediction:
 [[152.60432]
 [183.85149]
 [181.05183]
 [196.6268 ]
 [140.60605]]
------------------------------
3210 Cost:  1.0210087 
Prediction:
 [[152.6009 ]
 [183.85384]
 [181.0508 ]
 [196.62596]
 [140.60922]]
------------------------------
3220 Cost:  1.0166951 
Prediction:
 [[152.59747]
 [183.8562 ]
 [181.04974]
 [196.62512]
 [140.61238]]
------------------------------
3230 Cost:  1.0124273 
Prediction:
 [[152.59407]
 [183.85854]
 [181.04872]
 [196.62428]
 [140.61554]]
------------------------------
3240 Cost:  1.0081778 
Prediction:
 [[152.59068]
 [183.86089]
 [181.04771]
 [196.62346]
 [140.6187 ]]
------------------------------
3250 Cost:  1.003935 
Prediction:
 [[152.58728]
 [183.86322]
 [181.04668]
 [196.62262]
 [140.62184]]
------------------------------
3260 Cost:  0.99971867 
Prediction:
 [[152.5839 ]
 [183.86554]
 [181.0