In [1]:
import tensorflow as tf
import numpy as np

xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

# plcaceholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())
for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")

# Ask my score
print("Your score will be ", sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))
print("Other scores will be ", sess.run(hypothesis, feed_dict={X: [[60,70,110], [90,100,80]]}))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
0 Cost:  40637.13 
Prediction:
 [[-33.47242 ]
 [-44.365807]
 [-41.589035]
 [-45.551598]
 [-34.591934]
 [-26.266735]
 [-33.22896 ]
 [-23.325573]
 [-42.67588 ]
 [-40.387775]
 [-32.98108 ]
 [-34.405445]
 [-42.8125  ]
 [-35.487762]
 [-34.01805 ]
 [-44.869354]
 [-34.768425]
 [-39.134327]
 [-40.137577]
 [-35.484978]
 [-39.516716]
 [-

400 Cost:  13.312969 
Prediction:
 [[155.52469]
 [183.59682]
 [182.5907 ]
 [198.84665]
 [139.26094]
 [102.3868 ]
 [149.85652]
 [112.58161]
 [170.86299]
 [158.02455]
 [143.39621]
 [139.95732]
 [188.55501]
 [156.54384]
 [150.0569 ]
 [186.6224 ]
 [148.06349]
 [180.55711]
 [180.27454]
 [161.68938]
 [175.207  ]
 [172.48225]
 [167.33147]
 [156.64793]
 [190.77124]]
------------------------------
410 Cost:  13.249591 
Prediction:
 [[155.51317]
 [183.6013 ]
 [182.58522]
 [198.84636]
 [139.26422]
 [102.40013]
 [149.85963]
 [112.58801]
 [170.8784 ]
 [158.05305]
 [143.39882]
 [139.97018]
 [188.54384]
 [156.52763]
 [150.06342]
 [186.63069]
 [148.04686]
 [180.5602 ]
 [180.26015]
 [161.67557]
 [175.21126]
 [172.49084]
 [167.33235]
 [156.62343]
 [190.77034]]
------------------------------
420 Cost:  13.186792 
Prediction:
 [[155.50172 ]
 [183.60577 ]
 [182.57976 ]
 [198.84608 ]
 [139.26749 ]
 [102.413414]
 [149.86273 ]
 [112.5944  ]
 [170.89374 ]
 [158.08142 ]
 [143.40143 ]
 [139.98297 ]
 [188.53273 ]

940 Cost:  10.583016 
Prediction:
 [[154.97133]
 [183.81242]
 [182.32689]
 [198.83351]
 [139.4179 ]
 [103.0282 ]
 [150.00708]
 [112.89147]
 [171.60368]
 [159.39525]
 [143.52222]
 [140.57524]
 [188.01735]
 [155.76408]
 [150.37004]
 [187.02112]
 [147.2613 ]
 [180.70697]
 [179.58272]
 [161.02475]
 [175.41255]
 [172.89568]
 [167.37462]
 [155.46895]
 [190.72743]]
------------------------------
950 Cost:  10.543815 
Prediction:
 [[154.9623 ]
 [183.81593]
 [182.32256]
 [198.8333 ]
 [139.42044]
 [103.03866]
 [150.00957]
 [112.89657]
 [171.61577]
 [159.41765]
 [143.52428]
 [140.58533]
 [188.00856]
 [155.75131]
 [150.37517]
 [187.02762]
 [147.24815]
 [180.70944]
 [179.5714 ]
 [161.01389]
 [175.41591]
 [172.90242]
 [167.37532]
 [155.44968]
 [190.7267 ]]
------------------------------
960 Cost:  10.504934 
Prediction:
 [[154.9533 ]
 [183.81943]
 [182.31827]
 [198.83307]
 [139.42297]
 [103.04909]
 [150.01202]
 [112.90164]
 [171.6278 ]
 [159.43994]
 [143.52634]
 [140.59538]
 [187.9998 ]
 [155.73862]

1490 Cost:  8.869303 
Prediction:
 [[154.52992]
 [183.98366]
 [182.116  ]
 [198.82343]
 [139.54156]
 [103.53983]
 [150.1289 ]
 [113.14197]
 [172.19458]
 [160.49045]
 [143.62328]
 [141.06863]
 [187.58716]
 [155.13971]
 [150.62152]
 [187.33923]
 [146.61786]
 [180.82935]
 [179.02963]
 [160.49368]
 [175.57814]
 [173.22562]
 [167.41043]
 [154.52647]
 [190.69138]]
------------------------------
1500 Cost:  8.845256 
Prediction:
 [[154.52284]
 [183.98637]
 [182.11263]
 [198.82326]
 [139.54352]
 [103.54801]
 [150.13086]
 [113.146  ]
 [172.20403]
 [160.50795]
 [143.6249 ]
 [141.07652]
 [187.58026]
 [155.12968]
 [150.62553]
 [187.34431]
 [146.60751]
 [180.83131]
 [179.02075]
 [160.48518]
 [175.5808 ]
 [173.23088]
 [167.411  ]
 [154.51137]
 [190.69078]]
------------------------------
1510 Cost:  8.821413 
Prediction:
 [[154.51582]
 [183.9891 ]
 [182.10927]
 [198.82312]
 [139.54549]
 [103.55616]
 [150.13283]
 [113.15002]
 [172.21346]
 [160.52544]
 [143.62653]
 [141.0844 ]
 [187.57341]
 [155.11974]

2040 Cost:  7.818114 
Prediction:
 [[154.18512]
 [184.1167 ]
 [181.95091]
 [198.8159 ]
 [139.63678]
 [103.93948]
 [150.22559]
 [113.34055]
 [172.65622]
 [161.34755]
 [143.7027 ]
 [141.45445]
 [187.24998]
 [154.64989]
 [150.81944]
 [187.5878 ]
 [146.11209]
 [180.92743]
 [178.59647]
 [160.07805]
 [175.70892]
 [173.48341]
 [167.4396 ]
 [153.78848]
 [190.6623 ]]
------------------------------
2050 Cost:  7.8033495 
Prediction:
 [[154.17958]
 [184.11882]
 [181.94826]
 [198.81578]
 [139.63829]
 [103.94587]
 [150.22713]
 [113.34375]
 [172.66359]
 [161.36127]
 [143.70396]
 [141.46062]
 [187.24458]
 [154.64203]
 [150.82262]
 [187.59178]
 [146.10396]
 [180.92902]
 [178.58952]
 [160.0714 ]
 [175.71104]
 [173.48753]
 [167.44008]
 [153.77667]
 [190.66182]]
------------------------------
2060 Cost:  7.788724 
Prediction:
 [[154.17412]
 [184.12093]
 [181.94565]
 [198.81567]
 [139.6398 ]
 [103.95223]
 [150.2287 ]
 [113.34693]
 [172.67096]
 [161.37495]
 [143.70525]
 [141.46678]
 [187.23921]
 [154.63423

2600 Cost:  7.164154 
Prediction:
 [[153.91156]
 [184.22165]
 [181.81961]
 [198.81026]
 [139.71109]
 [104.25654]
 [150.30363]
 [113.50071]
 [173.02255]
 [162.02904]
 [143.76613]
 [141.76096]
 [186.98145]
 [154.25938]
 [150.97781]
 [187.7851 ]
 [145.70801]
 [181.0075 ]
 [178.25182]
 [159.74756]
 [175.81401]
 [173.68805]
 [167.46387]
 [153.20137]
 [190.63837]]
------------------------------
2610 Cost:  7.155189 
Prediction:
 [[153.90729 ]
 [184.2233  ]
 [181.81757 ]
 [198.81018 ]
 [139.71227 ]
 [104.261505]
 [150.30487 ]
 [113.50324 ]
 [173.02832 ]
 [162.03973 ]
 [143.76715 ]
 [141.76578 ]
 [186.97725 ]
 [154.25327 ]
 [150.98033 ]
 [187.7882  ]
 [145.70166 ]
 [181.00879 ]
 [178.24643 ]
 [159.7424  ]
 [175.81569 ]
 [173.69128 ]
 [167.46426 ]
 [153.19217 ]
 [190.638   ]]
------------------------------
2620 Cost:  7.1462865 
Prediction:
 [[153.903  ]
 [184.22493]
 [181.8155 ]
 [198.8101 ]
 [139.71341]
 [104.26644]
 [150.3061 ]
 [113.50576]
 [173.03401]
 [162.05037]
 [143.76813]
 [141.77055]

3150 Cost:  6.7719574 
Prediction:
 [[153.70229]
 [184.3014 ]
 [181.7189 ]
 [198.80624]
 [139.76689]
 [104.49904]
 [150.36452]
 [113.62545]
 [173.30284]
 [162.55157]
 [143.81502]
 [141.99573]
 [186.77518]
 [153.95909]
 [151.10013]
 [187.93608]
 [145.39653]
 [181.0707 ]
 [177.98735]
 [159.49417]
 [175.89552]
 [173.84468]
 [167.48337]
 [152.7509 ]
 [190.61937]]
------------------------------
3160 Cost:  6.7664547 
Prediction:
 [[153.69894 ]
 [184.30267 ]
 [181.71729 ]
 [198.80617 ]
 [139.76776 ]
 [104.50291 ]
 [150.3655  ]
 [113.627464]
 [173.30731 ]
 [162.55994 ]
 [143.8158  ]
 [141.99948 ]
 [186.77187 ]
 [153.95425 ]
 [151.10208 ]
 [187.93848 ]
 [145.39151 ]
 [181.0717  ]
 [177.98311 ]
 [159.49011 ]
 [175.89682 ]
 [173.8472  ]
 [167.48369 ]
 [152.7437  ]
 [190.61905 ]]
------------------------------
3170 Cost:  6.7609835 
Prediction:
 [[153.69563]
 [184.30396]
 [181.7157 ]
 [198.80614]
 [139.76868]
 [104.50677]
 [150.3665 ]
 [113.62947]
 [173.3118 ]
 [162.56827]
 [143.81659]
 [142.0032

3730 Cost:  6.5212293 
Prediction:
 [[153.5312 ]
 [184.36613]
 [181.63632]
 [198.80322]
 [139.81154]
 [104.69727]
 [150.41537]
 [113.72949]
 [173.53207]
 [162.97995]
 [143.85533]
 [142.18799]
 [186.60573]
 [153.71204]
 [151.2012 ]
 [188.05959]
 [145.13962]
 [181.12415]
 [177.77034]
 [159.2864 ]
 [175.9632 ]
 [173.97284]
 [167.50018]
 [152.38133]
 [190.60318]]
------------------------------
3740 Cost:  6.517937 
Prediction:
 [[153.52863]
 [184.36711]
 [181.63507]
 [198.80318]
 [139.81218]
 [104.70026]
 [150.41615]
 [113.73108]
 [173.5355 ]
 [162.98642]
 [143.85594]
 [142.19087]
 [186.60316]
 [153.70831]
 [151.20271]
 [188.06145]
 [145.13573]
 [181.12495]
 [177.76707]
 [159.28328]
 [175.96422]
 [173.97476]
 [167.50044]
 [152.37575]
 [190.60292]]
------------------------------
3750 Cost:  6.514682 
Prediction:
 [[153.52606 ]
 [184.36807 ]
 [181.63382 ]
 [198.80315 ]
 [139.81285 ]
 [104.703224]
 [150.41692 ]
 [113.73265 ]
 [173.53894 ]
 [162.99284 ]
 [143.85654 ]
 [142.19376 ]
 [186.60062 

In [2]:
import tensorflow as tf

filename_queue = tf.train.string_input_producer(['data-01-test-score.csv'], shuffle=False, name='filename_queue')
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

# Default values, in case of empty columns. Also specifies the type of the decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

# Collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size = 10)

# plcaceholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small Learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()

# Initializes global variables in the graph
sess.run(tf.global_variables_initializer())

# Start populating the filename queue
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)


for step in range(4001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train]
                                   , feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)
        print("------------------------------")

coord.request_stop()
coord.join(threads)

Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensors(tensor).repeat(num_epochs)`.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.
Instructions for updating:
Queue-base

280 Cost:  7.457473 
Prediction:
 [[152.0469  ]
 [186.15572 ]
 [181.48756 ]
 [199.15358 ]
 [141.70491 ]
 [107.42577 ]
 [150.53267 ]
 [113.479065]
 [176.72441 ]
 [167.47353 ]]
------------------------------
290 Cost:  7.437014 
Prediction:
 [[152.05243]
 [186.15178]
 [181.48929]
 [199.15376]
 [141.70064]
 [107.4188 ]
 [150.5333 ]
 [113.48051]
 [176.71622]
 [167.46132]]
------------------------------
300 Cost:  7.416565 
Prediction:
 [[152.05789]
 [186.1478 ]
 [181.49094]
 [199.1539 ]
 [141.69635]
 [107.41185]
 [150.53387]
 [113.48193]
 [176.70801]
 [167.4491 ]]
------------------------------
310 Cost:  7.396395 
Prediction:
 [[152.06337 ]
 [186.14388 ]
 [181.4926  ]
 [199.15408 ]
 [141.69211 ]
 [107.40493 ]
 [150.5345  ]
 [113.483376]
 [176.6999  ]
 [167.437   ]]
------------------------------
320 Cost:  7.3762426 
Prediction:
 [[152.06877]
 [186.13992]
 [181.49425]
 [199.15422]
 [141.68785]
 [107.39803]
 [150.53508]
 [113.48481]
 [176.69176]
 [167.42488]]
------------------------------

690 Cost:  6.729051 
Prediction:
 [[152.25497]
 [186.00433]
 [181.55043]
 [199.16028]
 [141.54047]
 [107.16198]
 [150.55824]
 [113.53872]
 [176.41414]
 [167.0135 ]]
------------------------------
700 Cost:  6.713867 
Prediction:
 [[152.25961]
 [186.0009 ]
 [181.55182]
 [199.16042]
 [141.53671]
 [107.15608]
 [150.55888]
 [113.5402 ]
 [176.4072 ]
 [167.0033 ]]
------------------------------
710 Cost:  6.6988525 
Prediction:
 [[152.26427 ]
 [185.99751 ]
 [181.5532  ]
 [199.1606  ]
 [141.53299 ]
 [107.150215]
 [150.55952 ]
 [113.54167 ]
 [176.40031 ]
 [166.99313 ]]
------------------------------
720 Cost:  6.6839514 
Prediction:
 [[152.26889 ]
 [185.99414 ]
 [181.5546  ]
 [199.16078 ]
 [141.5293  ]
 [107.14437 ]
 [150.56018 ]
 [113.543144]
 [176.39343 ]
 [166.98303 ]]
------------------------------
730 Cost:  6.6690736 
Prediction:
 [[152.27347]
 [185.99072]
 [181.55594]
 [199.16092]
 [141.52557]
 [107.13854]
 [150.56082]
 [113.54462]
 [176.38657]
 [166.97295]]
----------------------------

1140 Cost:  6.1456003 
Prediction:
 [[152.44687]
 [185.86221]
 [181.60703]
 [199.16782]
 [141.38385]
 [106.91917]
 [150.5878 ]
 [113.60519]
 [176.1286 ]
 [166.59592]]
------------------------------
1150 Cost:  6.134648 
Prediction:
 [[152.45074]
 [185.8593 ]
 [181.60815]
 [199.16797]
 [141.38063]
 [106.91425]
 [150.58847]
 [113.60666]
 [176.12282]
 [166.58754]]
------------------------------
1160 Cost:  6.123836 
Prediction:
 [[152.45462]
 [185.85643]
 [181.60928]
 [199.16815]
 [141.37743]
 [106.90937]
 [150.58916]
 [113.60815]
 [176.1171 ]
 [166.57922]]
------------------------------
1170 Cost:  6.1130214 
Prediction:
 [[152.45847 ]
 [185.85352 ]
 [181.61038 ]
 [199.1683  ]
 [141.3742  ]
 [106.904495]
 [150.58981 ]
 [113.60961 ]
 [176.11136 ]
 [166.5709  ]]
------------------------------
1180 Cost:  6.1024017 
Prediction:
 [[152.46233 ]
 [185.85068 ]
 [181.61153 ]
 [199.1685  ]
 [141.37103 ]
 [106.899666]
 [150.5905  ]
 [113.6111  ]
 [176.10568 ]
 [166.56267 ]]
-----------------------

1590 Cost:  5.723657 
Prediction:
 [[152.60704]
 [185.74132]
 [181.65298]
 [199.17537]
 [141.24863]
 [106.71693]
 [150.61797]
 [113.67114]
 [175.89081]
 [166.25348]]
------------------------------
1600 Cost:  5.715734 
Prediction:
 [[152.61029]
 [185.73886]
 [181.65392]
 [199.17554]
 [141.24585]
 [106.71283]
 [150.61864]
 [113.67259]
 [175.886  ]
 [166.24663]]
------------------------------
1610 Cost:  5.7079077 
Prediction:
 [[152.61353]
 [185.73642]
 [181.65485]
 [199.17572]
 [141.24307]
 [106.70876]
 [150.61932]
 [113.67404]
 [175.88126]
 [166.2398 ]]
------------------------------
1620 Cost:  5.70003 
Prediction:
 [[152.61673]
 [185.73393]
 [181.65573]
 [199.17587]
 [141.2403 ]
 [106.7047 ]
 [150.61996]
 [113.67548]
 [175.87645]
 [166.23297]]
------------------------------
1630 Cost:  5.692328 
Prediction:
 [[152.61995]
 [185.73152]
 [181.65666]
 [199.17607]
 [141.23755]
 [106.70066]
 [150.62065]
 [113.67693]
 [175.87172]
 [166.22623]]
------------------------------
1640 Cost:  5.6

2040 Cost:  5.4166026 
Prediction:
 [[152.74098 ]
 [185.63829 ]
 [181.69034 ]
 [199.18282 ]
 [141.13164 ]
 [106.54821 ]
 [150.64795 ]
 [113.735405]
 [175.69249 ]
 [165.97252 ]]
------------------------------
2050 Cost:  5.4108095 
Prediction:
 [[152.74371 ]
 [185.63617 ]
 [181.69109 ]
 [199.18298 ]
 [141.12923 ]
 [106.544785]
 [150.64862 ]
 [113.7368  ]
 [175.68849 ]
 [165.96687 ]]
------------------------------
2060 Cost:  5.405073 
Prediction:
 [[152.74641 ]
 [185.63408 ]
 [181.69183 ]
 [199.18315 ]
 [141.12683 ]
 [106.54139 ]
 [150.64928 ]
 [113.738205]
 [175.6845  ]
 [165.96127 ]]
------------------------------
2070 Cost:  5.3993382 
Prediction:
 [[152.7491  ]
 [185.63197 ]
 [181.69257 ]
 [199.1833  ]
 [141.12442 ]
 [106.537994]
 [150.64993 ]
 [113.73961 ]
 [175.68051 ]
 [165.95567 ]]
------------------------------
2080 Cost:  5.3936753 
Prediction:
 [[152.75179 ]
 [185.6299  ]
 [181.6933  ]
 [199.18347 ]
 [141.12204 ]
 [106.53462 ]
 [150.65059 ]
 [113.741005]
 [175.67654 ]
 [165.9

2490 Cost:  5.191724 
Prediction:
 [[152.85318 ]
 [185.55028 ]
 [181.72066 ]
 [199.19002 ]
 [141.03023 ]
 [106.4072  ]
 [150.67723 ]
 [113.797165]
 [175.52681 ]
 [165.7418  ]]
------------------------------
2500 Cost:  5.187463 
Prediction:
 [[152.85547 ]
 [185.54846 ]
 [181.72127 ]
 [199.19019 ]
 [141.02814 ]
 [106.404335]
 [150.67787 ]
 [113.7985  ]
 [175.52344 ]
 [165.73717 ]]
------------------------------
2510 Cost:  5.1832685 
Prediction:
 [[152.85774]
 [185.54668]
 [181.7219 ]
 [199.19035]
 [141.02606]
 [106.4015 ]
 [150.67851]
 [113.79985]
 [175.52013]
 [165.73257]]
------------------------------
2520 Cost:  5.179055 
Prediction:
 [[152.85999 ]
 [185.54488 ]
 [181.72247 ]
 [199.1905  ]
 [141.02397 ]
 [106.39866 ]
 [150.67915 ]
 [113.801186]
 [175.51678 ]
 [165.72798 ]]
------------------------------
2530 Cost:  5.1748676 
Prediction:
 [[152.86223 ]
 [185.54309 ]
 [181.72307 ]
 [199.19064 ]
 [141.0219  ]
 [106.395836]
 [150.67978 ]
 [113.80251 ]
 [175.51346 ]
 [165.7234  ]]
----

2940 Cost:  5.0260553 
Prediction:
 [[152.94734]
 [185.47491]
 [181.74529]
 [199.19691]
 [140.94215]
 [106.28912]
 [150.7054 ]
 [113.85588]
 [175.38812]
 [165.55222]]
------------------------------
2950 Cost:  5.022933 
Prediction:
 [[152.94926 ]
 [185.47337 ]
 [181.74579 ]
 [199.19707 ]
 [140.94034 ]
 [106.286736]
 [150.70602 ]
 [113.857155]
 [175.38531 ]
 [165.54842 ]]
------------------------------
2960 Cost:  5.0198064 
Prediction:
 [[152.95116]
 [185.47185]
 [181.74626]
 [199.19722]
 [140.93852]
 [106.28435]
 [150.70663]
 [113.85842]
 [175.38252]
 [165.54463]]
------------------------------
2970 Cost:  5.0167055 
Prediction:
 [[152.95306 ]
 [185.47029 ]
 [181.74675 ]
 [199.19736 ]
 [140.9367  ]
 [106.281975]
 [150.70724 ]
 [113.85968 ]
 [175.37973 ]
 [165.54086 ]]
------------------------------
2980 Cost:  5.0136137 
Prediction:
 [[152.95494]
 [185.46875]
 [181.74722]
 [199.19751]
 [140.93489]
 [106.27961]
 [150.70784]
 [113.86095]
 [175.37694]
 [165.5371 ]]
----------------------

3390 Cost:  4.903386 
Prediction:
 [[153.02652]
 [185.41026]
 [181.76527]
 [199.20345]
 [140.86551]
 [106.19008]
 [150.73221]
 [113.91121]
 [175.27184]
 [165.3963 ]]
------------------------------
3400 Cost:  4.901067 
Prediction:
 [[153.02812]
 [185.40895]
 [181.76569]
 [199.20361]
 [140.86392]
 [106.18806]
 [150.73279]
 [113.91239]
 [175.26949]
 [165.39317]]
------------------------------
3410 Cost:  4.8987427 
Prediction:
 [[153.02972 ]
 [185.40762 ]
 [181.76608 ]
 [199.20374 ]
 [140.86234 ]
 [106.186066]
 [150.73337 ]
 [113.9136  ]
 [175.26712 ]
 [165.39005 ]]
------------------------------
3420 Cost:  4.8964324 
Prediction:
 [[153.03133]
 [185.4063 ]
 [181.76646]
 [199.20387]
 [140.86076]
 [106.18407]
 [150.73395]
 [113.91478]
 [175.26479]
 [165.38695]]
------------------------------
3430 Cost:  4.894163 
Prediction:
 [[153.03293 ]
 [185.405   ]
 [181.76688 ]
 [199.20403 ]
 [140.85919 ]
 [106.182076]
 [150.73453 ]
 [113.91596 ]
 [175.26245 ]
 [165.38387 ]]
------------------------

3840 Cost:  4.81209 
Prediction:
 [[153.09322 ]
 [185.35468 ]
 [181.7815  ]
 [199.2096  ]
 [140.79868 ]
 [106.106804]
 [150.75748 ]
 [113.96298 ]
 [175.17413 ]
 [165.26794 ]]
------------------------------
3850 Cost:  4.810379 
Prediction:
 [[153.09459 ]
 [185.35356 ]
 [181.78183 ]
 [199.20973 ]
 [140.79732 ]
 [106.10512 ]
 [150.75806 ]
 [113.964096]
 [175.17216 ]
 [165.26538 ]]
------------------------------
3860 Cost:  4.808667 
Prediction:
 [[153.09595]
 [185.35242]
 [181.78217]
 [199.20987]
 [140.79593]
 [106.10344]
 [150.75859]
 [113.9652 ]
 [175.17018]
 [165.26282]]
------------------------------
3870 Cost:  4.8069196 
Prediction:
 [[153.09727]
 [185.35126]
 [181.78247]
 [199.20999]
 [140.79456]
 [106.10175]
 [150.75912]
 [113.96631]
 [175.16821]
 [165.26025]]
------------------------------
3880 Cost:  4.805217 
Prediction:
 [[153.09862 ]
 [185.35014 ]
 [181.78279 ]
 [199.21013 ]
 [140.79318 ]
 [106.100075]
 [150.75967 ]
 [113.96741 ]
 [175.16624 ]
 [165.2577  ]]
----------------

In [ ]:
# min_after_dequeue defines how big a buffer we will randomly sample
# from -- bigger means better shuffling but slower start up and more
# memory used.
# capacity must be larger than min_after)dequeue and the amount larger
# determines the maximum we will prefetch.
# Recommendation: min_after_dequeue + (num_threads + a small safety margin) * batch_size

min_after_dequeue = 10000
capacity = min_after_dequeue + 3 * batch_size
example_batch, label_batch = tf.train.shuffle_batch([example, label], batch_size=batch_size, capacity=capacity,
                                                    min_after_dequeue = min_after_dequeue)